//EN
// Language
#define T_HEADER            "OSSM Remote"
#define T_BLANK             ""
#define T_MENU              "Menu"
#define T_MENUE             "Menu"         // legacy alias
#define T_DEMO              "Demo"
#define T_CONNECT           "Connect"
#define T_SETTINGS          "Settings"
#define T_MOTD              "Welcome to OSSM M5 Remote"
#define T_BATT              "Battery"
#define T_CREAMPIE          "Pullout"
#define T_START             "Start"
#define T_STOP              "STOP"
#define T_PAUSE             "Pause"
#define T_CUM               "Cum"
#define T_HOME              "Home"
#define T_BACK              "Back"
#define T_SELECT            "Select"
#define T_MEN1              "Up"
#define T_MEN2              "Down"
#define T_SPEED             "Speed:"
#define T_DEPTH             "Depth:"
#define T_MM                " mm"
#define T_STROKE            "Stroke:"
#define T_SENSATION         "Sensation:"
#define T_SETUP_DEPTH_I     "Set Depth Interactively"
#define T_SETUP_DEPTH_F     "Set Depth Fancy"
#define T_SELECT_PATTERN    "Select Pattern"
#define T_PATTERN_Button    "Select Pattern \n Menu"
#define T_RESTART           "Restart"
#define T_SETUP_TORQE       "Setup Torque"
#define T_OUT_TORQE         "Outward Torque:"
#define T_IN_TORQE          "Inward Torque:"
#define T_EJECT_SETTINGS    "EJECT Settings"
#define T_EJECT             "EJECT"
#define T_SAVE              "Save"
#define T_LOW               "Low"
#define T_HIGH              "High"
#define T_VIBRATE           "Vibrate"
#define T_TOUCHSETTING      "Touch Disabled"
#define T_STROKEINVERT      "Stroke inverted"
#define T_HOME_FORCE        "BLE Force Homing"

// New screens / UI-MENU
#define T_HOMESCREEN        "Home screen"
#define T_HOMESCREEN_SUB    "(Stroke engine)"
#define T_STREAMING         "Streaming"
#define T_STREAMING_SUB     "mode"
#define T_STROKE_SCREEN     "Bator mode"
#define T_STROKE_SUB        "(stroker)"
#define T_ADDONS            "Addons"

// Screen titles (logos / headers)
#define T_SCREEN_START      "OSSM Remote"
#define T_SCREEN_HOME       "OSSM Home"
#define T_SCREEN_MENU       "Menu"
#define T_SCREEN_STREAMING  "Streaming"
#define T_SCREEN_SETTINGS   "Settings"
#define T_SCREEN_ADDONS     "Addons"
#define T_SCREEN_COLORS     "Color Schemes"
#define T_SCREEN_PATTERN    "Pattern"
#define T_SCREEN_TORQUE     "Torque"
#define T_SCREEN_EJECT      "CUM pump"
#define T_SCREEN_STROKE     "Bator mode"

// Colors / addons screen
#define T_ADDONS_HINT             "Assign addons via left / right button"
#define T_ADDONS_SLOT_LEFT        "Left"
#define T_ADDONS_SLOT_RIGHT       "Right"
#define T_ADDONS_SLOT_OFF         "Off"

#define T_Patterns          "Pattern:"
#define T_SimpleStroke      "Simple Stroke"
#define T_TeasingPounding   "Teasing or Pounding"
#define T_RoboStroke        "Robo Stroke"
#define T_HalfnHalf         "Half 'n' Half"
#define T_Deeper            "Deeper"
#define T_StopNGo           "Stop'n'Go"
#define T_Insist            "Insist"
#define T_JackHammer        "Jack Hammer"
#define T_StrokeNibbler     "Stroke Nibbler"
#define T_Knot              "Knot"

#define T_CUM_SPEED         "CUM Speed"
#define T_CUM_TIME          "CUM Time"
#define T_CUM_Volume        "CUM Volume"
#define T_CUM_Accel         "CUM Force"

#define T_FUCKS_MIN         " F/m"
