//EN
// Language
#define T_HEADER            "OSSM Remote"
#define T_BLANK             ""
#define T_MENU             "Menu"
#define T_DEMO              "Demo"
#define T_CONNECT           "Connect"
#define T_CONNECTING        "Connecting..."
#define T_CONNECTED         "Connected"
#define T_DISCONNECTED      "Disconnected" 
#define T_LONG_WAIT         "This takes longer than expected..."
#define T_FAILED            "Connection/Homing failed"
#define T_HOMING            "Homing..."
#define T_BLECONNECTED      "Connected via Bluetooth"
#define T_ESPCONNECTED      "Connected via Wifi (ESP-NOW)"
#define T_SETTINGS          "Settings"
#define T_MOTD              "Welcome to OSSM M5 Remote"
#define T_BATT              "Battery"
#define T_CREAMPIE          "Pullout"
#define T_START             "Start"
#define T_CLICK_RESUME      "Click to Home/resume"
#define T_RESUME            "Resume"
#define T_RUNNING           "Running"
#define T_PAUSE             "Pause"
#define T_STOP              "STOP"
#define T_FAIL              "Failed"
#define T_BLOCKED           "Blocked/Not Ready"
#define T_CUM               "Cum"
#define T_HOME              "Home"
#define T_MEN1              "Up"
#define T_MEN2              "Down"
#define T_SPEED             "Speed:"
#define T_DEPTH             "Depth:"
#define T_MM                " mm"
#define T_STROKE            "Stroke:"
#define T_SENSATION         "Sensation:"
#define T_SETUP_DEPTH_I     "Set Depth Interactively"
#define T_SETUP_DEPTH_F     "Set Depth Fancy"
#define T_SELECT_PATTERN    "Select Pattern"
#define T_PATTERN_Button    "Select Pattern \n Menue"
#define T_RESTART           "Restart"
#define T_SETUP_TORQE       "Setup Torque"
#define T_OUT_TORQE         "Outward Torque:"
#define T_IN_TORQE          "Inward Torque:"
#define T_EJECT_SETTINGS    "EJECT Settings"
#define T_EJECT             "EJECT"
#define T_SELECT            "Select"
#define T_OPEN              "Open"
#define T_SAVE              "Save"
#define T_LOW               "Low"
#define T_HIGH              "High"
#define T_DARKM             "Dark Mode"
#define T_VIBRATE           "Vibrate"
#define T_TOUCHSETTING      "Touch Disabled"
#define T_STROKEINVERT      "Stroke inverted"
#define T_SLEEP             "Sleep"
#define T_ESP_NOW           "ESP-NOW"
#define T_CHARGING_WARNING_TITLE "Caution - Charging"
#define T_CHARGING_WARNING_TEXT  "When charging, stability issues can occur. \n\nIt is best to not use the M5 remote to control your toys now."

#define T_Patterns          "Pattern:"
#define T_SimpleStroke      "Simple Stroke"
#define T_TeasingPounding   "Teasing or Pounding"
#define T_RoboStroke        "Robo Stroke"
#define T_HalfnHalf         "Half 'n' Half"
#define T_Deeper            "Deeper"
#define T_StopNGo           "Stop'n'Go"
#define T_Insist            "Insist"
#define T_JackHammer        "Jack Hammer"
#define T_StrokeNibbler     "Stroke Nibbler"
#define T_Knot              "Knot"

#define T_CUM_SPEED         "Speed"
#define T_CUM_TIME          "Shots"
#define T_CUM_Volume        "Volume"
#define T_CUM_Accel         "Force"
#define T_ROTATION          "Rotation"
#define T_ACCEL             "Accel"
#define T_FUCKS_MIN         " F/m"

// UI_MENU buttons
#define T_HOMESCREEN        "Home screen"
#define T_HOMESCREEN_SUB    "(Stroke engine)"
#define T_STREAMING         "Streaming"
#define T_STREAMING_SUB     "mode"
#define T_ADDONS            "Addons"
#define T_PATTERN_GENERATOR "Pattern Generator"
#define T_OVERRIDE          "Override"  //was added, but removed now (safety)
#define T_STOP_STREAMING    "Stop streaming"
#define T_STREAMING_CAUTION_TITLE "Caution - Homing"
#define T_STREAMING_CAUTION_TEXT  "The OSSM will now start a homing procedure. Move away from the OSSM for your safety"
#define T_STREAMING_ACTIVE_TITLE  "OSSM in Streaming mode"
#define T_STREAMING_ACTIVE_TEXT   "The OSSM is now in STREAMING MODE. \nPress START to arm streaming.\nMovement begins when an external stream source sends position frames."
#define T_STREAMING_RUNNING_TITLE "OSSM Streaming mode active"
#define T_STREAMING_RUNNING_TEXT  "Your OSSM is now in active streaming mode. Your M5 remote does not have control anymore. You can safely shut down the M5 remote, or stop streaming mode."
#define T_STREAMING_FAIL_TITLE    "Streaming failed"
#define T_STREAMING_FAIL_TEXT     "The OSSM could not enter streaming mode."

// Screen titles
#define T_SCREEN_START            "Start"
#define T_SCREEN_STROKE_ENGINE    "OSSM Home"
// Stroke screen title
#define T_SCREEN_STROKE          "Stroke"
#define T_SCREEN_MENU             "Menu"
#define T_SCREEN_STREAMING        "Streaming"
#define T_SCREEN_SETTINGS         "Settings"
#define T_SCREEN_ADDONS           "Addons"
#define T_SCREEN_COLORS           "Color Schemes"
#define T_SCREEN_PATTERN          "Pattern"
#define T_SCREEN_TORQUE           "Torque"
#define T_SCREEN_EJECT            "Eject CUMpump"

// Addons screen
#define T_ADDONS_HINT             "Click addon to assign: Left -> Right -> Off"
#define T_ADDONS_SLOT_LEFT        "Left"
#define T_ADDONS_SLOT_RIGHT       "Right"
#define T_ADDONS_SLOT_OFF         "Off"
#define T_BACK                    "Back"
